# Automatic Caching 

Hera allows the automatic caching of a function using the decorator cache Function 

To use it first import it. 

In [1]:
from hera import cacheFunction,datatypes,clearFunctionCache
from hera.utils import *

Now for example lets define the function computeTheItem. 

In [2]:
import numpy 
import time 

@cacheFunction
def computeTheItem(param1,param2,param3):
    time.sleep(2)
    return [param1,param2,param3]

In [3]:
computeTheItem(1,2,numpy.array([1,2]))

> /home/yehudaa/Development/hera/hera/datalayer/autocache.py(149)__call__()
    147 
    148         # Add the function name
--> 149         call_info_serialized['functionName'] =  self._get_full_func_name(self.func)
    150 
    151         data = self.checkIfFunctionIsCached(call_info_serialized)



ipdb>  c


> /home/yehudaa/Development/hera/hera/datalayer/project.py(738)addData()
    736         import pdb
    737         pdb.set_trace()
--> 738         guessedDataFormat = self.datatypes.getDataFormatName(data) if dataFormat is None else dataFormat
    739 
    740         handler = self.datatypes.getHandler(guessedDataFormat)



ipdb>  unt


> /home/yehudaa/Development/hera/hera/datalayer/project.py(740)addData()
    738         guessedDataFormat = self.datatypes.getDataFormatName(data) if dataFormat is None else dataFormat
    739 
--> 740         handler = self.datatypes.getHandler(guessedDataFormat)
    741         file_extension = self.datatypes.getDataFormatExtension(data)
    742 



ipdb>  v


*** NameError: name 'v' is not defined


ipdb>  guessedDataFormat


'pickle'


ipdb>  c


[1, 2, array([1, 2])]

In [7]:
computeTheItem(1,4,3)

array([1, 4, 3])

In [8]:
computeTheItem(1,2,3)

array([1, 2, 3])

In [14]:
computeTheItem(1,2,5)

array([1, 2, 5])

In [2]:
import pandas

class exampleClass:
    @cacheFunction
    def computeClassMethod(self,param1,param2,param3):
        return pandas.Series(numpy.array([param1,param2,param3]))  

In [8]:
exmaple = exampleClass()
aa = exmaple.computeClassMethod(4,5,numpy.array([1,2))

In [15]:
from hera import Project 
proj = Project()

In [16]:
proj.getCacheDocuments(functionName= "computeTheItem")

[<Cache: {
    "_cls": "Metadata.Cache",
    "projectName": "testProject",
    "desc": {
        "param1": 1,
        "param2": 2,
        "param3": 5,
        "functionName": "computeTheItem",
        "storeParameters": {}
    },
    "type": "functionCacheData",
    "resource": "/home/yehudaa/Development/hera/hera/doc/jupyter/datalayer/cache/computeTheItem_10.npy",
    "dataFormat": "numpy_array"
}>]

In [12]:
clearFunctionCache(functionName="computeTheItem")

True

In [13]:
import pickle
import base64

# Serialize an object into a plain text
def obj_to_txt(obj):
    message_bytes = pickle.dumps(obj)
    base64_bytes = base64.b64encode(message_bytes)
    txt = base64_bytes.decode('ascii')
    return txt

# De-serialize an object from a plain text
def txt_to_obj(txt):
    base64_bytes = txt.encode('ascii')
    message_bytes = base64.b64decode(base64_bytes)
    obj = pickle.loads(message_bytes)
    return obj


In [22]:
# Some class for demonstration
class Demo:
    x = None
    def __init__(self):
        # It has some data which can be serialized
        self.some_data = "hello"
        self.x = numpy.array([1,2])

    def say_hello(self):
        print(self.some_data)

In [23]:
d = Demo()

In [25]:
txt = obj_to_txt(d)

In [26]:
newObj = txt_to_obj(txt)

In [28]:
newObj.say_hello()

hello


In [7]:
from bson import json_util
import json

In [10]:
json_str = obj_to_txt(numpy.array([1,2]))

In [15]:
txt_to_obj(json_str)

array([1, 2])

In [17]:
is_mongo_serializable(numpy.array([1,2]))


False