# Automatic Caching 

Hera allows the automatic caching of a function using the decorator cache Function 

To use it first import it. 

In [1]:
from hera import cacheFunction,datatypes,clearFunctionCache
from hera.utils import *

Now for example lets define the function computeTheItem. 

In [2]:
import numpy 
import time 

@cacheFunction
def computeTheItem(param1,param2,param3):
    time.sleep(2)
    return numpy.array([param1,param2,param3])

In [3]:
computeTheItem(1,2,3)

array([1, 2, 3])

In [4]:
computeTheItem(1,4,3)

array([1, 4, 3])

In [5]:
computeTheItem(1,2,3)

array([1, 2, 3])

In [2]:
import pandas

class exampleClass:
    @cacheFunction
    def computeClassMethod(self,param1,param2,param3):
        return pandas.Series(numpy.array([param1,param2,param3]))  

In [8]:
exmaple = exampleClass()
aa = exmaple.computeClassMethod(4,5,6)

In [9]:
clearFunctionCache("computeTheItem")

True

In [6]:
from hera import Project 
proj = Project()

In [9]:
proj.getCacheDocuments(functionName= "computeTheItem")

[<Cache: {
    "_cls": "Metadata.Cache",
    "projectName": "testProject",
    "desc": {
        "param1": 1,
        "param2": 2,
        "param3": 3,
        "functionName": "computeTheItem",
        "storeParameters": {}
    },
    "type": "functionCacheData",
    "resource": "/home/yehudaa/Development/hera/hera/doc/jupyter/datalayer/cache/computeTheItem_7.npy",
    "dataFormat": "numpy_array"
}>, <Cache: {
    "_cls": "Metadata.Cache",
    "projectName": "testProject",
    "desc": {
        "param1": 1,
        "param2": 4,
        "param3": 3,
        "functionName": "computeTheItem",
        "storeParameters": {}
    },
    "type": "functionCacheData",
    "resource": "/home/yehudaa/Development/hera/hera/doc/jupyter/datalayer/cache/computeTheItem_8.npy",
    "dataFormat": "numpy_array"
}>]

In [9]:
clearFunctionCache(functionName="computeTheItem")

True